
2020-06-28 20:36:40,733 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:43:13,150 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:43:35,672 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:44:55,324 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:45:52,329 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:46:11,734 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:47:34,960 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:50:06,363 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:50:34,313 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:51:35,841 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:51:56,069 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:56:46,771 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:58:40,365 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:00:04,335 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:01:21,515 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:04:42,013 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:05:24,180 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:06:26,576 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:07:11,274 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:07:27,041 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:13:53,705 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:15:15,869 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:20:28,123 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:21:27,194 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:56:33,669 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:04:09,016 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:04:36,515 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:05:02,354 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:05:40,873 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:07:40,165 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:07:58,709 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:08:29,137 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:08:41,666 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:00,942 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:13,241 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:34,479 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:45,891 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:10:02,391 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:11:06,598 INFO: errors [in app.py:621]
2020-06-28 22:30:59,667 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:34,525 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:44,728 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:54,381 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:37:42,732 INFO: errors [in app.py:600]
2020-06-28 22:37:56,129 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:38:02,277 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:38:27,743 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:41:22,426 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:43:27,693 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:45:52,418 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = find_current_date()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:45:54,191 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = find_current_date()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:59:44,463 INFO: errors [in app.py:600]
2020-06-28 22:59:53,403 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:02:59,155 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    #     date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:03:15,968 INFO: errors [in app.py:600]
2020-06-28 23:03:23,516 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in template
    <h6>{{ show.start_time|datetime('full') }}</h6>
jinja2.exceptions.TemplateAssertionError: no filter named 'datetime'
2020-06-28 23:04:08,917 INFO: errors [in app.py:600]
2020-06-28 23:04:18,109 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:05:13,848 INFO: errors [in app.py:600]
2020-06-28 23:08:07,721 INFO: errors [in app.py:600]
2020-06-28 23:08:18,969 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show.date > current_date:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
2020-06-28 23:15:44,842 INFO: errors [in app.py:606]
2020-06-28 23:15:49,853 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 243, in show_venue
    'upcoming_shows': find_upcoming_shows(),
  File "app.py", line 218, in find_upcoming_shows
    upcoming_show_artist = Artist.query.get(upcoming_show.artist_id)
AttributeError: 'Venue' object has no attribute 'artist_id'
2020-06-28 23:17:26,671 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 243, in show_venue
    #         'image_link': venue.image_link,
  File "app.py", line 218, in find_upcoming_shows
    # def find_upcoming_shows():
AttributeError: 'Venue' object has no attribute 'artist_id'
2020-06-28 23:21:58,651 INFO: errors [in app.py:600]
2020-06-28 23:22:08,046 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show.date > current_date:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
2020-06-28 23:30:56,202 INFO: errors [in app.py:601]
2020-06-28 23:31:02,517 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:51:49,399 INFO: errors [in app.py:600]
2020-06-29 18:52:12,288 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:56:05,535 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:56:31,566 INFO: errors [in app.py:600]
2020-06-29 18:56:39,558 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:59:38,938 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:04:21,159 INFO: errors [in app.py:600]
2020-06-29 19:04:29,161 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:09:33,496 INFO: errors [in app.py:600]
2020-06-29 19:09:37,427 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:20:25,239 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    venue = list(filter(lambda d: d['id'] ==
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:20:37,321 INFO: errors [in app.py:602]
2020-06-29 19:20:41,423 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 190, in show_venue
    Show.start_time.strftime("%m/%d/%Y, %H:%M") < datetime.now()).all()
AttributeError: type object 'Show' has no attribute 'start_time'
2020-06-29 19:21:26,719 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 190, in show_venue
    shows.start_time.strftime("%m/%d/%Y, %H:%M") < datetime.now()).all()
AttributeError: type object 'Show' has no attribute 'start_time'
2020-06-29 19:21:38,422 INFO: errors [in app.py:602]
2020-06-29 19:21:41,494 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 189, in show_venue
    past_shows = db.session.query(shows).join(Artist).filter(shows.venue_id == venue_id).filter(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\sqlalchemy\orm\session.py", line 1584, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\sqlalchemy\orm\query.py", line 199, in __init__
    self._set_entities(entities)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\sqlalchemy\orm\query.py", line 225, in _set_entities
    entity_wrapper(self, ent)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\sqlalchemy\orm\query.py", line 4666, in __init__
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '[<Show 1>]'
2020-06-29 19:22:45,705 INFO: errors [in app.py:600]
2020-06-29 19:22:49,597 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:23:18,215 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:23:26,865 INFO: errors [in app.py:600]
2020-06-29 19:23:29,098 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show_date > current_date:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
2020-06-29 19:23:57,006 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show_date > current_date:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
2020-06-29 19:24:09,935 INFO: errors [in app.py:600]
2020-06-29 19:24:12,955 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:25:11,747 INFO: errors [in app.py:600]
2020-06-29 19:25:14,378 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show_date > current_date:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
2020-06-29 19:25:56,961 INFO: errors [in app.py:600]
2020-06-29 19:26:01,423 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show_date > current_date:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
2020-06-29 19:26:36,656 INFO: errors [in app.py:600]
2020-06-29 19:26:41,049 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:27:39,039 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:28:24,352 INFO: errors [in app.py:600]
2020-06-29 19:28:29,017 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:31:08,886 INFO: errors [in app.py:601]
2020-06-29 19:31:16,535 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 95, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:34:03,419 INFO: errors [in app.py:601]
2020-06-29 19:34:08,131 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 196, in show_venue
    if show_date > current_date:
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
2020-06-29 19:34:40,850 INFO: errors [in app.py:601]
2020-06-29 19:34:44,917 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 95, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:36:43,229 INFO: errors [in app.py:601]
2020-06-29 19:36:47,993 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 66, in block "content"
    {%for show in venue.past_shows %}
TypeError: 'NoneType' object is not iterable
2020-06-29 19:45:00,945 INFO: errors [in app.py:601]
2020-06-29 19:45:06,356 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 66, in block "content"
    {%for show in venue.past_shows %}
TypeError: 'NoneType' object is not iterable
2020-06-29 19:47:54,930 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:601]
2020-06-29 19:49:05,746 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:601]
2020-06-29 19:54:29,728 INFO: errors [in app.py:601]
2020-06-29 19:54:34,099 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 66, in block "content"
    {%for show in venue.past_shows %}
TypeError: 'NoneType' object is not iterable
2020-06-29 19:59:20,936 INFO: errors [in app.py:609]
2020-06-29 20:00:48,709 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:609]
2020-06-29 20:06:28,356 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:610]
2020-06-29 20:07:03,130 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:610]
2020-06-29 20:08:24,859 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:610]
2020-06-29 20:09:18,284 INFO: errors [in app.py:617]
2020-06-29 20:16:05,930 INFO: errors [in app.py:612]
2020-06-29 20:23:46,185 INFO: errors [in app.py:613]
2020-06-29 20:23:53,936 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 226, in show_venue
    upcoming_shows_data = find_upcoming_shows()
  File "app.py", line 221, in find_upcoming_shows
    'artist_name': upcoming_show_artist.name,
AttributeError: 'BaseQuery' object has no attribute 'name'
2020-06-29 20:23:59,869 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 226, in show_venue
    upcoming_shows_data = find_upcoming_shows()
  File "app.py", line 221, in find_upcoming_shows
    'artist_name': upcoming_show_artist.name,
AttributeError: 'BaseQuery' object has no attribute 'name'
2020-06-29 20:51:28,600 INFO: errors [in app.py:612]
2020-06-29 20:52:50,038 INFO: errors [in app.py:611]
2020-06-29 20:52:56,326 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 252, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 66, in block "content"
    {%for show in venue.past_shows %}
TypeError: 'NoneType' object is not iterable
2020-06-29 20:54:27,225 INFO: errors [in app.py:614]
2020-06-29 20:56:15,847 INFO: errors [in app.py:617]
2020-06-29 21:06:21,042 INFO: errors [in app.py:622]
2020-06-29 21:06:36,763 ERROR: Exception on /artists/3 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 410, in show_artist
    'address': artist.address,
AttributeError: 'Artist' object has no attribute 'address'
2020-06-29 21:09:12,498 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:09:21,938 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:09:34,441 INFO: errors [in app.py:622]
2020-06-29 21:12:11,884 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:14:34,676 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:17:42,994 INFO: errors [in app.py:622]
2020-06-29 21:20:41,547 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:25:51,013 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:622]
2020-06-29 21:26:00,709 INFO: errors [in app.py:622]
2020-06-29 21:27:23,097 ERROR: Exception on /artists/create [POST] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\forms.py", line 212, in validate_phone
    raise ValidationError('Invalid phone number.')
wtforms.validators.ValidationError: Invalid phone number.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 495, in create_artist_form
    if form.validate_on_submit():
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask_wtf\form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\form.py", line 150, in validate
    if not field.validate(self, extra):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\fields\core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\fields\core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\forms.py", line 214, in validate_phone
    input_number = phonenumbers.parse("+1"+field.data)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\phonenumbers\phonenumberutil.py", line 2799, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2020-06-29 22:07:47,538 INFO: errors [in app.py:611]
2020-06-29 22:09:11,433 INFO: errors [in app.py:612]
2020-06-29 22:09:13,890 ERROR: Exception on /shows [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 563, in shows
    return render_template('pages/shows.html', shows=data)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\shows.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\shows.html", line 9, in block "content"
    <h4>{{ show.start_time|datetime('full') }}</h4>
  File "app.py", line 96, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 22:09:36,362 ERROR: Exception on /shows [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 563, in shows
    return render_template('pages/shows.html', shows=data)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\shows.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\shows.html", line 9, in block "content"
    <h4>{{ show.start_time|datetime('full') }}</h4>
  File "app.py", line 96, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 22:09:43,335 INFO: errors [in app.py:612]
2020-06-29 22:14:36,534 INFO: errors [in app.py:592]
2020-06-29 22:16:09,948 ERROR: Exception on /venues/create [POST] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\forms.py", line 97, in validate_phone
    raise ValidationError('Invalid phone number.')
wtforms.validators.ValidationError: Invalid phone number.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 246, in create_venue_form
    if form.validate_on_submit():
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask_wtf\form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\form.py", line 150, in validate
    if not field.validate(self, extra):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\fields\core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\wtforms\fields\core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\forms.py", line 99, in validate_phone
    input_number = phonenumbers.parse("+1"+field.data)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\phonenumbers\phonenumberutil.py", line 2799, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2020-06-29 22:19:53,237 INFO: errors [in app.py:589]
2020-06-29 22:20:42,264 INFO: errors [in app.py:589]
2020-06-29 22:27:53,421 INFO: errors [in app.py:593]
2020-06-29 22:28:07,879 ERROR: Exception on /venues/8/delete [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-29 22:28:50,754 INFO: errors [in app.py:593]
2020-06-29 22:32:14,444 INFO: errors [in app.py:573]
2020-06-29 22:35:15,668 INFO: errors [in app.py:573]
2020-06-29 22:36:17,459 INFO: errors [in app.py:573]
2020-06-29 22:36:34,075 INFO: errors [in app.py:573]
2020-06-29 22:36:37,790 ERROR: Exception on /artists/5/edit [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 411, in edit_artist
    return render_template('forms/edit_artist.html', form=form, artist=artist)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\forms\edit_artist.html", line 9, in template
    {{ form.name(class_ = 'form-control', placeholder={{ artist.name }},
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2020-06-29 22:39:50,501 INFO: errors [in app.py:573]
2020-06-29 22:46:25,837 INFO: errors [in app.py:573]
2020-06-29 23:01:07,951 INFO: errors [in app.py:596]
