
2020-06-28 20:36:40,733 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:43:13,150 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:43:35,672 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:44:55,324 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:45:52,329 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:46:11,734 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:47:34,960 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:50:06,363 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:50:34,313 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:51:35,841 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:51:56,069 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:56:46,771 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 20:58:40,365 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:00:04,335 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:01:21,515 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:04:42,013 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:05:24,180 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:06:26,576 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:07:11,274 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:07:27,041 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:13:53,705 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:15:15,869 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:20:28,123 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:21:27,194 INFO: errors [in C:\Users\Noyan_Ali\Desktop\FSND\projects\01_fyyur\starter_code\app.py:621]
2020-06-28 21:56:33,669 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:04:09,016 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:04:36,515 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:05:02,354 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:05:40,873 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:07:40,165 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:07:58,709 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:08:29,137 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:08:41,666 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:00,942 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:13,241 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:34,479 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:09:45,891 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:10:02,391 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:11:06,598 INFO: errors [in app.py:621]
2020-06-28 22:30:59,667 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:34,525 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:44,728 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:32:54,381 INFO: errors [in C:\Users\Noyan_Ali\Desktop\fyyur-udacity\app.py:621]
2020-06-28 22:37:42,732 INFO: errors [in app.py:600]
2020-06-28 22:37:56,129 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:38:02,277 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:38:27,743 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:41:22,426 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:43:27,693 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = datetime
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:45:52,418 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = find_current_date()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:45:54,191 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 194, in show_venue
    current_date = find_current_date()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2020-06-28 22:59:44,463 INFO: errors [in app.py:600]
2020-06-28 22:59:53,403 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:02:59,155 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    #     date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:03:15,968 INFO: errors [in app.py:600]
2020-06-28 23:03:23,516 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in template
    <h6>{{ show.start_time|datetime('full') }}</h6>
jinja2.exceptions.TemplateAssertionError: no filter named 'datetime'
2020-06-28 23:04:08,917 INFO: errors [in app.py:600]
2020-06-28 23:04:18,109 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-28 23:05:13,848 INFO: errors [in app.py:600]
2020-06-28 23:08:07,721 INFO: errors [in app.py:600]
2020-06-28 23:08:18,969 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show.date > current_date:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
2020-06-28 23:15:44,842 INFO: errors [in app.py:606]
2020-06-28 23:15:49,853 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 243, in show_venue
    'upcoming_shows': find_upcoming_shows(),
  File "app.py", line 218, in find_upcoming_shows
    upcoming_show_artist = Artist.query.get(upcoming_show.artist_id)
AttributeError: 'Venue' object has no attribute 'artist_id'
2020-06-28 23:17:26,671 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 243, in show_venue
    #         'image_link': venue.image_link,
  File "app.py", line 218, in find_upcoming_shows
    # def find_upcoming_shows():
AttributeError: 'Venue' object has no attribute 'artist_id'
2020-06-28 23:21:58,651 INFO: errors [in app.py:600]
2020-06-28 23:22:08,046 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 195, in show_venue
    if show.date > current_date:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'str'
2020-06-28 23:30:56,202 INFO: errors [in app.py:601]
2020-06-28 23:31:02,517 ERROR: Exception on /venues/7 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 245, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:51:49,399 INFO: errors [in app.py:600]
2020-06-29 18:52:12,288 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=data3)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:56:05,535 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:56:31,566 INFO: errors [in app.py:600]
2020-06-29 18:56:39,558 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 18:59:38,938 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
2020-06-29 19:04:21,159 INFO: errors [in app.py:600]
2020-06-29 19:04:29,161 ERROR: Exception on /venues/6 [GET] [in C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 244, in show_venue
    return render_template('pages/show_venue.html', venue=venue)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\layouts\main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Noyan_Ali\Desktop\fyyur-udacity\templates\pages\show_venue.html", line 57, in block "content"
    <h6>{{ show.start_time|datetime('full') }}</h6>
  File "app.py", line 94, in format_datetime
    date = dateutil.parser.parse(value)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 192, in split
    return list(cls(s))
  File "C:\Users\Noyan_Ali\Anaconda3\envs\myflaskenv\lib\site-packages\dateutil\parser.py", line 60, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not datetime
